### ISSUE TITLE
PHP 8.0 com_finder array issue / solution review

### ISSUE THREAD

**Issue by breebee** [joomla-framework/console#8]
### Steps to reproduce the issue
Use smart search component on the frontend with a test query

### Expected result
Show search results

### Actual result
0 array_merge() does not accept unknown named parameters 

### System information (as much as possible)
Joomla 4 Beta 8 - Dev
PHP 8.0 - fpm
NGINX

### Additional comments
I have fixed / bypassed error as follows

components/com_finder/src/Model/SearchModel.php line 289

- $include = call_user_func_array('array_merge', $this->includedTerms);
+ $include = call_user_func_array('array_merge', array_values($this->includedTerms));

**Comment by alikon** [comment]
you should open this issue on the CMS repo https://github.com/joomla/joomla-cms/
here is for the console framework

**Comment by breebee** [comment]
Ok posting now.
